name: Build FFmpeg 4.3.1 Static Libraries for Windows x64 and x86

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]

    steps:
    # Checkout FFmpeg repository at version 4.3.1
    - name: Checkout FFmpeg
      uses: actions/checkout@v4
      with:
        repository: FFmpeg/FFmpeg
        ref: n4.3.1

    # Install MSYS2
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.arch == 'x64' && 'MINGW64' || 'MINGW32' }}
        update: true
        install: mingw-w64-${{ matrix.arch }}-gcc mingw-w64-${{ matrix.arch }}-make

    # Install Visual Studio Build Tools
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{ matrix.arch }}

    # Configure FFmpeg for static libraries
    - name: Configure FFmpeg
      run: |
        ./configure \
          --arch=${{ matrix.arch }} \
          --toolchain=msvc \
          --enable-static \
          --disable-shared \
          --disable-programs \
          --disable-doc \
          --enable-libavcodec \
          --enable-libavutil \
          --enable-libswresample \
          --extra-cflags="-MT" \
          --extra-ldflags="-LIBPATH:${{ env.MINGW_PREFIX }}/lib"
      shell: msys2 {0}
      env:
        MINGW_PREFIX: ${{ matrix.arch == 'x64' && 'C:/msys64/mingw64' || 'C:/msys64/mingw32' }}

    # Build FFmpeg
    - name: Build FFmpeg
      run: |
        make -j$(nproc)
      shell: msys2 {0}

    # Collect and upload artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-4.3.1-${{ matrix.arch }}-release-static
        path: |
          libavcodec/libavcodec.lib
          libavutil/libavutil.lib
          libswresample/libswresample.lib
        if-no-files-found: error
