name: Build HP-Socket Static x64 with SSL

on:
  workflow_dispatch:
  push:
    tags:
      - 'v6.*'

jobs:
  build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      PLATFORM: x64
      HP_SOCKET_VERSION: v6.6.0

    steps:
    - name: Clone HP-Socket source
      run: |
        git clone --branch %HP_SOCKET_VERSION% https://github.com/ldcsaa/HP-Socket.git
        cd HP-Socket
        echo "HP_SOCKET_DIR=$PWD/HP-Socket" >> $env:GITHUB_ENV

    - name: Install OpenSSL (1.1.1)
      run: |
        choco install openssl --version=1.1.1.2100 -y
        echo "INCLUDE=C:\Program Files\OpenSSL-Win64\include" >> $env:GITHUB_ENV
        echo "LIB=C:\Program Files\OpenSSL-Win64\lib" >> $env:GITHUB_ENV

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build HP-Socket static lib
      run: |
        cd HP-Socket
        msbuild builds\vs2022\hpsocket-static.sln `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:SSL_SUPPORT=true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hp-socket-static-x64-release
        path: HP-Socket/bin/x64/Release/*.lib
