name: Build HP-Socket Static Library with SSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [Win32, x64]

    env:
      OPENSSL_ROOT_DIR: C:\Program Files\OpenSSL-Win64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install vcpkg and OpenSSL
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install openssl:x64-windows
          .\vcpkg\vcpkg install openssl:x86-windows

      - name: Configure CMake
        run: >
          cmake -B build_${{ matrix.arch }} -A ${{ matrix.arch }}
          -DHPSSL_SUPPORT=ON
          -DHP_STATIC=ON
          -DOPENSSL_ROOT_DIR="${{ env.OPENSSL_ROOT_DIR }}"
          -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build Release
        run: cmake --build build_${{ matrix.arch }} --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HP-Socket-${{ matrix.arch }}-Release
          path: build_${{ matrix.arch }}/Release/*.lib
