name: Build HP-Socket Static x64 with SSL (v6.0.4)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v6.0.4'

jobs:
  build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      PLATFORM: x64
      HP_SOCKET_VERSION: v6.0.4

    steps:
    - name: Clone HP-Socket v6.0.4 source
      run: |
        git clone --branch ${{ env.HP_SOCKET_VERSION }} https://github.com/ldcsaa/HP-Socket.git

    - name: Install OpenSSL (v1.1.1)
      run: |
        choco install openssl --version=1.1.1.2100 -y
        echo "INCLUDE=C:\Program Files\OpenSSL-Win64\include" >> $env:GITHUB_ENV
        echo "LIB=C:\Program Files\OpenSSL-Win64\lib" >> $env:GITHUB_ENV

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build HP-Socket static lib from correct .sln
      run: |
        cd HP-Socket
        msbuild Windows\Project\HPSocket-2022.sln `
          /p:Configuration=${{ env.CONFIGURATION }} `
          /p:Platform=${{ env.PLATFORM }} `
          /p:SSL_SUPPORT=true `
          /t:HPSocket_Static

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hp-socket-v6.0.4-static-x64-release
        path: |
          HP-Socket/bin/x64/Release/*.lib
