name: Build FFmpeg 4.3 Static for Windows x64 with .lib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install MSYS2 and Tools
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          yasm
          unzip
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-llvm

    - name: Build FFmpeg 4.3
      shell: msys2 {0}
      run: |
        cd /c
        git clone --branch release/4.3 https://github.com/FFmpeg/FFmpeg.git ffmpeg
        cd ffmpeg
        ./configure \
          --prefix=/c/ffmpeg_build \
          --toolchain=mingw64 \
          --arch=x86_64 \
          --target-os=mingw32 \
          --enable-static \
          --disable-shared \
          --disable-debug \
          --disable-programs \
          --disable-doc \
          --enable-avcodec \
          --enable-avutil \
          --enable-swresample
        make -j$(nproc)
        make install

    - name: Convert .a to .lib (using llvm-dlltool)
      shell: msys2 {0}
      run: |
        cd /c/ffmpeg_build/lib
        for lib in *.a; do
          base=$(basename "$lib" .a)
          llvm-dlltool -m i386:x86-64 -D dummy.dll -l "$base.lib" "$lib"
        done

    - name: Package .lib and includes
      shell: bash
      run: |
        cd /c/ffmpeg_build
        mkdir package
        cp -r include package/
        mkdir package/lib
        cp lib/*.lib package/lib/
        zip -r ffmpeg-static-x64-4.3-lib.zip package

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-static-x64-4.3-lib
        path: /c/ffmpeg_build/ffmpeg-static-x64-4.3-lib.zip
