name: Build HP-Socket Static x64 with SSL

on:
  push:
    tags:
      - 'v6.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      CONFIGURATION: Release
      PLATFORM: x64

    steps:
    - name: Checkout HP-Socket source
      uses: actions/checkout@v3

    - name: Install OpenSSL prebuilt (v1.1.1 or v3.x)
      run: |
        choco install openssl --version=1.1.1.2100 -y
        echo "INCLUDE=C:\Program Files\OpenSSL-Win64\include" >> $env:GITHUB_ENV
        echo "LIB=C:\Program Files\OpenSSL-Win64\lib" >> $env:GITHUB_ENV

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build static lib (x64 Release)
      run: |
        msbuild builds\vs2022\hpsocket-static.sln `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:SSL_SUPPORT=true

    - name: Archive Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hp-socket-static-x64-release
        path: |
          bin/x64/Release/*.lib
          bin/x64/Release/*.pdb
          bin/x64/Release/*.dll
          bin/x64/Release/*.exe

    - name: (Optional) Publish Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/x64/Release/*.lib
          bin/x64/Release/*.pdb
          bin/x64/Release/*.dll
          bin/x64/Release/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
