name: Build zlib Static Libraries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'zlib version tag (e.g. v1.3.1)'
        required: true
        default: 'v1.3.1'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, Win32]

    steps:
    - name: Checkout zlib
      uses: actions/checkout@v4
      with:
        repository: madler/zlib
        ref: ${{ github.event.inputs.version }}

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF

    - name: Build
      run: cmake --build build --config Release

    - name: Upload static library
      uses: actions/upload-artifact@v4
      with:
        name: zlib-${{ matrix.arch }}-Release
        path: build/Release/*.lib
