name: Build zlib Static Libraries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'zlib version to build'
        required: true
        default: 'v1.3.1'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - name: Checkout zlib source
      uses: actions/checkout@v4
      with:
        repository: madler/zlib
        ref: ${{ github.event.inputs.version }}

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF

    - name: Build
      run: cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zlib-${{ matrix.arch }}-release
        path: build/Release/*.lib
