name: Build HP-Socket x64 Static Library with SSL

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout your project
        uses: actions/checkout@v3

      - name: Clone HP-Socket source
        run: |
          git clone --depth=1 --branch=master https://github.com/ldcsaa/HP-Socket.git

      - name: Install vcpkg and OpenSSL x64
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg install openssl:x64-windows

      - name: Configure CMake (x64 static + ssl)
        run: >
          cmake -S HP-Socket -B build_x64 -A x64
          -DHPSSL_SUPPORT=ON
          -DHP_STATIC=ON
          -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build Release (x64)
        run: cmake --build build_x64 --config Release --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HP-Socket-x64-Release
          path: build_x64/Release/*.lib
